name: peg

services:
  php-cli:
    container_name: php-peg
    build:
      context: ./
    platform: linux/amd64
    env_file: ".env"
    volumes:
      - ./output:/app/output
      - ./source:/app/source
    ports:
      - "8007:80"
