services:
  portal-entity-repository-generator:
    image: portal-entity-repository-generator:latest
    platform: linux/amd64
    build: .
    env_file: ".env"
    environment:
      FOREGROUND_PROCESS: php-fpm
      CONTAINER_ENABLED: 1
    volumes:
      - ./output:/app/output
      - ./source:/app/source
    ports:
      - "8007:80"
